/* Start Header *****************************************************************/
/*!
\file   ComponentInspectorUI.h
\author Foo Rui Qin (100%)
\par    ruiqin.foo@digipen.edu
\date   3rd November 2025
\brief
Provides unified component rendering UI for both entity inspection and prefab editing.
Features:
- Reusable component rendering functions for all component types
- JSON-based interface works with both live entities and prefab files
- Bidirectional conversion between C++ components and JSON representation
- Consistent UI layout across entity inspector and prefab editor
References:
- ImGui documentation for UI widgets and styling
- nlohmann/json for data manipulation
- EditorUIHelpers for property rendering widgets
*/
/* End Header *******************************************************************/
#ifndef COMPONENT_INSPECTOR_UI_H
#define COMPONENT_INSPECTOR_UI_H

#include <nlohmann/json.hpp>
#include <imgui.h>
#include "ecs/Components.h"
#include "serialization/EntitySerializer.h"  // For to_json/from_json

namespace ComponentUI {
    // Call once to set fonts for rendering
    void Initialize(ImFont* mainFont, ImFont* boldFont, ImFont* symbolsFont);

    // Render functions that work on BOTH JSON and live components
    void RenderTransform(nlohmann::json& data);
    void RenderSpriteRenderer(nlohmann::json& data);
    void RenderRigidbody2D(nlohmann::json& data);
    void RenderCircleCollider2D(nlohmann::json& data);
    void RenderBoxCollider2D(nlohmann::json& data);
    void RenderShapeRenderer2D(nlohmann::json& data);
    void RenderLineRenderer(nlohmann::json& data);

    // WHY WE NEED THIS:
    // This lets us use ONE set of Render*() functions for BOTH prefabs and entities
    // Prefabs store data as JSON files > can be edited directly
    // Entities store data as C++ structs in memory > need conversion to edit with the same UI

    // ComponentToJson: converts live C++ component into JSON format for editing
    // JsonToComponent: applies edited JSON values back to the C++ component
    // These use to_json/from_json auto-generated by NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE
    template<typename T>
    inline nlohmann::json ComponentToJson(const T& component) {
        nlohmann::json j;
        to_json(j, component);
        return j;
    }

    template<typename T>
    inline void JsonToComponent(const nlohmann::json& data, T& component) {
        from_json(data, component);
    }
}

#endif // COMPONENT_INSPECTOR_UI_H