/* Start Header *****************************************************************/
/*!
\file   ComponentInspectorUI.h
\author Foo Rui Qin (100%)
\par    ruiqin.foo@digipen.edu
\date   3rd November 2025
\brief
Provides unified component rendering UI for both entity inspection and prefab editing.

Features:
- Reusable component rendering functions for all component types
- JSON-based interface works with both live entities and prefab files
- Bidirectional conversion between C++ components and JSON representation
- Consistent UI layout across entity inspector and prefab editor

References:
- ImGui documentation for UI widgets and styling
- nlohmann/json for data manipulation
- EditorUIHelpers for property rendering widgets
*/
/* End Header *******************************************************************/
#ifndef COMPONENT_INSPECTOR_UI_H
#define COMPONENT_INSPECTOR_UI_H

#include <nlohmann/json.hpp>
#include <imgui.h>
#include "ecs/Components.h"
#include "serialization/EntitySerializer.h"  // For to_json/from_json

class ComponentUI {
public:
    // Set fonts used by component UI rendering
    void Initialize(ImFont* mainFont, ImFont* boldFont, ImFont* symbolsFont);

    // Render functions that work on BOTH JSON and live components
    // Updated to match new ECS::Components namespace
    // Render Local Transform properties
    void RenderLocalTransform(nlohmann::json& data);        
    // Render Sprite Renderer 2D properties
    void RenderSpriteRenderer2D(nlohmann::json& data);      
    // Render Rigidbody 2D physical parameters
    void RenderRigidbody2D(nlohmann::json& data);           
    // Render Linear Velocity 2D component
    void RenderLinearVelocity2D(nlohmann::json& data);
    // Render Angular Velocity 2D component
    void RenderAngularVelocity2D(nlohmann::json& data);
    // Render Circle Collider 2D properties
    void RenderCircleCollider2D(nlohmann::json& data);      
    // Render Box Collider 2D properties
    void RenderBoxCollider2D(nlohmann::json& data);         
    // Render Shape Circle 2D data
    void RenderShapeCircle2D(nlohmann::json& data);         
    // Render Shape Box 2D data
    void RenderShapeBox2D(nlohmann::json& data);            
    // Render Shape Line 2D data
    void RenderShapeLine2D(nlohmann::json& data);

    // Render Camera 3D projection and clipping parameters
    void RenderCamera3D(nlohmann::json& data);

    // This lets us use ONE set of Render*() functions for BOTH prefabs and entities
    // Prefabs store data as JSON files that can be edited directly
    // Entities store data as C++ structs in memory that need conversion to edit with the same UI

    // ComponentToJson: converts C++ component -> JSON (for editing)
    template<typename T>
    nlohmann::json ComponentToJson(const T& component) {
        nlohmann::json j;
        to_json(j, component);
        return j;
    }

    // JsonToComponent: applies edited JSON -> C++ component (round-trip)
    template<typename T>
    void JsonToComponent(const nlohmann::json& data, T& component) {
        from_json(data, component);
    }

    // Uses to_json/from_json (auto-generated by NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE)
    // Round-trip: ComponentToJson -> UI edits `Data` -> JsonToComponent

private:
    // Main font for standard text
    ImFont* m_mainFont;
    // Bold font for headers and labels
    ImFont* m_boldFont;
    // Symbols font for icons and glyphs
    ImFont* m_symbolsFont;
};

#endif