/* Start Header *****************************************************************/
/*!
\file   ComponentInspectorUI.h
\author Foo Rui Qin (100%)
\par    ruiqin.foo@digipen.edu
\date   3rd November 2025
\brief
Provides unified component rendering UI for both entity inspection and prefab editing.

Features:
- Reusable component rendering functions for all component types
- JSON-based interface works with both live entities and prefab files
- Bidirectional conversion between C++ components and JSON representation
- Consistent UI layout across entity inspector and prefab editor

References:
- ImGui documentation for UI widgets and styling
- nlohmann/json for data manipulation
- EditorUIHelpers for property rendering widgets
*/
/* End Header *******************************************************************/
#ifndef COMPONENT_INSPECTOR_UI_H
#define COMPONENT_INSPECTOR_UI_H

#include <nlohmann/json.hpp>
#include <imgui.h>
#include "ecs/Components.h"
#include "serialization/EntitySerializer.h"  // For to_json/from_json

class ComponentUI {
public:
    // This sets fonts for component UI
    // It keeps headers labels and icons consistent
    void Initialize(ImFont* mainFont, ImFont* boldFont, ImFont* symbolsFont);

    // Render functions that work on BOTH JSON and live components
    // Updated to match new ECS::Components namespace
    // This edits position rotation and scale
    // It writes values back to the JSON data
    void RenderLocalTransform(nlohmann::json& data);        
    // This edits sprite material and tint
    // It writes changes to the JSON data
    void RenderSpriteRenderer2D(nlohmann::json& data);      
    // This edits mass drag and gravity toggle
    // It applies values to the JSON data
    void RenderRigidbody2D(nlohmann::json& data);           
    // This edits linear velocity
    // It updates the JSON values
    void RenderLinearVelocity2D(nlohmann::json& data);
    // This edits angular velocity
    // It updates the JSON values
    void RenderAngularVelocity2D(nlohmann::json& data);
    // This edits radius and offset
    // It writes data to JSON
    void RenderCircleCollider2D(nlohmann::json& data);      
    // This edits size and offset
    // It writes data to JSON
    void RenderBoxCollider2D(nlohmann::json& data);         
    // This edits shape circle data
    // It updates the JSON fields
    void RenderShapeCircle2D(nlohmann::json& data);         
    // This edits shape box data
    // It updates the JSON fields
    void RenderShapeBox2D(nlohmann::json& data);            
    // This edits shape line data
    // It updates the JSON fields
    void RenderShapeLine2D(nlohmann::json& data);
    // This edits Audio src data
    // It updates the JSON fields
    void RenderAudioSource(nlohmann::json& data);


    // This edits projection and clipping
    // It writes values to the JSON data
    void RenderCamera3D(nlohmann::json& data);

    // This lets us use ONE set of Render*() functions for BOTH prefabs and entities
    // Prefabs store data as JSON files that can be edited directly
    // Entities store data as C++ structs in memory that need conversion to edit with the same UI

    // This turns a C++ component into JSON
    // It uses to_json to fill the data
    template<typename T>
    nlohmann::json ComponentToJson(const T& component) {
        nlohmann::json j;
        to_json(j, component);
        return j;
    }

    // This applies JSON back to a C++ component
    // It uses from_json to set fields
    template<typename T>
    void JsonToComponent(const nlohmann::json& data, T& component) {
        from_json(data, component);
    }

    // Uses to_json/from_json (auto-generated by NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE)
    // Round-trip: ComponentToJson -> UI edits `Data` -> JsonToComponent

private:
    // Main font for standard text
    ImFont* m_mainFont;
    // Bold font for headers and labels
    ImFont* m_boldFont;
    // Symbols font for icons and glyphs
    ImFont* m_symbolsFont;
};

#endif