<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.19.57" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\api\GrapeEngine.Scripting\GrapeEngine.Scripting.csproj" />
  </ItemGroup>
</Project>
