/* Start Header *****************************************************************/
/*!
\file   EditorComponentRegistry.cpp
\author Foo Rui Qin (100%)
\par    ruiqin.foo@digipen.edu
\date   15th November 2025

\brief
Implements the metadata registry used by the editor to describe every component
type that can appear in the inspector. Each entry stores display names and
functions for creating and cloning JSON definitions of components.

To add a new component:
1. Add entry to m_registry below
2. Implement RenderXXX() function in ComponentPropertyEditor.cpp
3. Done: no need to modify InspectorPanel.cpp
*/
/* End Header *******************************************************************/

#include "EditorComponentRegistry.h"
#include "ComponentPropertyEditor.h"
#include "serialization/EntitySerializer.h" 

/* 
Helper macro to reduce repetition when registering components

This macro expands into FOUR operations for a component type T:
1. canCheck: check if an entity HAS this component
2. apply: add/update the component using JSON data
3. remove: remove the component from the entity
4. applyPrefab: same as apply, used for prefab instances

The backslash at the end of each line tells the compiler that the macro continues on the next line
Without these, the macro would end early and break the expansion
*/
#define COMPONENT_OPS(T) \
    /* Check if entity already has component T; the lambda returns a bool */ \
    /* BUT the lambda has no name and no fixed type which is why we wrap it into a standard function object */ \
    /* static_cast converts the lambda into a std::function by wrapping it */ \
    static_cast<std::function<bool(ECS::World*, ECS::Entity)>>([](ECS::World* w, ECS::Entity e) { return w->Has<T>(e); }), \
    \
    /* Apply component data from JSON; if entity doesn't have T, add it then load values from JSON */ \
    /* into the component using from_json(d, c) */ \
    static_cast<std::function<void(ECS::World*, ECS::Entity, const nlohmann::json&)>>([](ECS::World* w, ECS::Entity e, const nlohmann::json& d) { \
        /* Add component if missing */ \
        if (!w->Has<T>(e)) w->Add<T>(e); \
        /* Get reference to component T on this entity and then fill component fields using JSON */ \
        auto& c = w->Get<T>(e); \
        from_json(d, c); \
    }), \
    \
    /* Remove component T from the entity */ \
    static_cast<std::function<void(ECS::World*, ECS::Entity)>>([](ECS::World* w, ECS::Entity e) { w->Remove<T>(e); }), \
    \
    /* Apply component data again (used for prefab instance overrides) */ \
    /* Same logic as above */ \
    static_cast<std::function<void(ECS::World*, ECS::Entity, const nlohmann::json&)>>([](ECS::World* w, ECS::Entity e, const nlohmann::json& d) { \
        if (!w->Has<T>(e)) w->Add<T>(e); \
        auto& c = w->Get<T>(e); \
        from_json(d, c); \
    })

// ============================================================================
// Metadata Structure
// ============================================================================

// Initialize the registry: ONE PLACE for all components
static std::vector<ComponentUIMetadata> m_registry = {
    // Transform: cannot be deleted (every entity has one)
    {
        // Display name, short name, fully qualified type and cannot be deleted
        "Transform", "LocalTransform", "ECS::Components::LocalTransform", false,

        // UI renderer callback: the Inspector calls this function, which forwards 
        // to ComponentWidgets to draw the UI
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderLocalTransform(d, e, w); },

        // Default values: created when adding a Transform to a new entity
        []() { return nlohmann::json{
            {"Position", {{"X", 0.0f}, {"Y", 0.0f}, {"Z", 0.0f}}},
            {"Rotation", {{"X", 0.0f}, {"Y", 0.0f}, {"Z", 0.0f}, {"W", 1.0f}}},
            {"Scale", {{"X", 1.0f}, {"Y", 1.0f}, {"Z", 1.0f}}}
        }; },

        // ECS operations generated by the macro
        COMPONENT_OPS(ECS::Components::LocalTransform)
    },

    // Name
    {
        "Name", "Name", "ECS::Components::Name", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderName(d, e, w); },
        []() { return nlohmann::json{{"Value", "Entity"}}; },
        COMPONENT_OPS(ECS::Components::Name)
    },

    // Active
    {
        "Active", "Active", "ECS::Components::Active", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderActive(d, e, w); },
        []() { return nlohmann::json{{"Enabled", true}}; },
        COMPONENT_OPS(ECS::Components::Active)
    },

    // Tag Mask
    {
        "Tag Mask", "TagMask", "ECS::Components::TagMask", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderTagMask(d, e, w); },
        []() { return nlohmann::json{{"Mask", 0}}; },
        COMPONENT_OPS(ECS::Components::TagMask)
    },

    // Lifetime
    {
        "Lifetime", "Lifetime", "ECS::Components::Lifetime", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderLifetime(d, e, w); },
        []() { return nlohmann::json{{"Time", 0.0f}}; },
        COMPONENT_OPS(ECS::Components::Lifetime)
    },

    // Camera 3D
    // EVERYTHING FROM THIS POINT IS JUST THE SAME THING
    {
        "Camera 3D", "Camera3D", "ECS::Components::Camera3D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderCamera3D(d, e, w); },
        []() { return nlohmann::json{
            {"UsePerspective", false}, {"FOV", 45.0f}, {"NearPlane", 0.1f},
            {"FarPlane", 100.0f}, {"OrthoSize", 10.0f},
            {"AspectRatio", 16.0f / 9.0f}, {"Active", false}
        }; },
        COMPONENT_OPS(ECS::Components::Camera3D)
    },

    // Sprite Renderer 2D
    {
        "Sprite Renderer 2D", "SpriteRenderer2D", "ECS::Components::SpriteRenderer2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderSpriteRenderer2D(d, e, w); },
        []() { return nlohmann::json{
            {"TextureId", 0},
            {"Color", {{"R", 1.0f}, {"G", 1.0f}, {"B", 1.0f}, {"A", 1.0f}}},
            {"Tiling", {{"X", 1.0f}, {"Y", 1.0f}}},
            {"Offset", {{"X", 0.0f}, {"Y", 0.0f}}},
            {"Width", 0}, {"Height", 0}
        }; },
        COMPONENT_OPS(ECS::Components::SpriteRenderer2D)
    },

    // Sprite Sheet Animation 2D
    {
        "Sprite Sheet Animation 2D", "SpriteSheetAnimation2D", "ECS::Components::SpriteSheetAnimation2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderSpriteSheetAnimation2D(d, e, w); },
        []() { return nlohmann::json{
            {"TextureId", 0}, {"FrameWidth", 32}, {"FrameHeight", 32},
            {"SheetWidth", 256}, {"SheetHeight", 256},
            {"StartFrame", 0}, {"FrameCount", 1}, {"FramesPerSecond", 10.0f},
            {"Loop", true}, {"Playing", false}
        }; },
        COMPONENT_OPS(ECS::Components::SpriteSheetAnimation2D)
    },

    // Z-Index 2D
    {
        "Z-Index 2D", "ZIndex2D", "ECS::Components::ZIndex2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderZIndex2D(d, e, w); },
        []() { return nlohmann::json{
            {"ZOrder", 0}
        }; },
        COMPONENT_OPS(ECS::Components::ZIndex2D)
    },

    // Rigidbody 2D
    {
        "Rigidbody 2D", "Rigidbody2D", "ECS::Components::Rigidbody2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderRigidbody2D(d, e, w); },
        []() { return nlohmann::json{
            {"Mass", 1.0f}, {"InverseMass", 1.0f},
            {"LinearDamping", 0.0f}, {"AngularDamping", 0.0f},
            {"GravityScale", 1.0f}, {"Flags", 0}
        }; },
        COMPONENT_OPS(ECS::Components::Rigidbody2D)
    },

    // Linear Velocity 2D
    {
        "Linear Velocity 2D", "LinearVelocity2D", "ECS::Components::LinearVelocity2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderLinearVelocity2D(d, e, w); },
        []() { return nlohmann::json{
            {"Value", {{"X", 0.0f}, {"Y", 0.0f}}}
        }; },
        COMPONENT_OPS(ECS::Components::LinearVelocity2D)
    },

    // Angular Velocity 2D
    {
        "Angular Velocity 2D", "AngularVelocity2D", "ECS::Components::AngularVelocity2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderAngularVelocity2D(d, e, w); },
        []() { return nlohmann::json{
            {"Value", 0.0f}
        }; },
        COMPONENT_OPS(ECS::Components::AngularVelocity2D)
    },

    // Acceleration 2D
    {
        "Acceleration 2D", "Acceleration2D", "ECS::Components::Acceleration2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderAcceleration2D(d, e, w); },
        []() { return nlohmann::json{
            {"Value", {{"X", 0.0f}, {"Y", 0.0f}}}
        }; },
        COMPONENT_OPS(ECS::Components::Acceleration2D)
    },

    // Physics Material 2D
    {
        "Physics Material 2D", "PhysicsMaterial2D", "ECS::Components::PhysicsMaterial2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderPhysicsMaterial2D(d, e, w); },
        []() { return nlohmann::json{
            {"Friction", 0.5f}, {"Restitution", 0.0f}, {"PositionCorrectPercent", 0.2f}
        }; },
        COMPONENT_OPS(ECS::Components::PhysicsMaterial2D)
    },

    // Circle Collider 2D
    {
        "Circle Collider 2D", "CircleCollider2D", "ECS::Components::CircleCollider2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderCircleCollider2D(d, e, w); },
        []() { return nlohmann::json{
            {"Radius", 0.5f},
            {"Offset", {{"X", 0.0f}, {"Y", 0.0f}}},
            {"LayerMask", 0xFFFFFFFFu}, {"Flags", 0}
        }; },
        COMPONENT_OPS(ECS::Components::CircleCollider2D)
    },

    // Box Collider 2D
    {
        "Box Collider 2D", "BoxCollider2D", "ECS::Components::BoxCollider2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderBoxCollider2D(d, e, w); },
        []() { return nlohmann::json{
            {"HalfExtents", {{"X", 0.5f}, {"Y", 0.5f}}},
            {"Offset", {{"X", 0.0f}, {"Y", 0.0f}}},
            {"Rotation", 0.0f},
            {"LayerMask", 0xFFFFFFFFu}, {"Flags", 0}
        }; },
        COMPONENT_OPS(ECS::Components::BoxCollider2D)
    },

    // Shape Circle 2D
    {
        "Shape Circle", "ShapeCircle2D", "ECS::Components::ShapeCircle2D", true,
            [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderShapeCircle2D(d, e, w); },
            []() { return nlohmann::json{
                {"Radius", 0.5f},
                {"Offset", {{"X", 0.0f}, {"Y", 0.0f}}},
                {"Color", {{"R", 1.0f}, {"G", 1.0f}, {"B", 1.0f}, {"A", 1.0f}}},
                {"Thickness", 1.0f}, {"Filled", false}
        }; },
            COMPONENT_OPS(ECS::Components::ShapeCircle2D)
    },

    // Shape Box 2D
    {
        "Shape Box", "ShapeBox2D", "ECS::Components::ShapeBox2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderShapeBox2D(d, e, w); },
        []() { return nlohmann::json{
            {"HalfExtents", {{"X", 0.5f}, {"Y", 0.5f}}},
            {"Offset", {{"X", 0.0f}, {"Y", 0.0f}}},
            {"Color", {{"R", 1.0f}, {"G", 1.0f}, {"B", 1.0f}, {"A", 1.0f}}},
            {"Thickness", 0.1f}, {"Filled", false}
        }; },
        COMPONENT_OPS(ECS::Components::ShapeBox2D)
    },

    // Shape Line 2D
    {
        "Shape Line", "ShapeLine2D", "ECS::Components::ShapeLine2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderShapeLine2D(d, e, w); },
        []() { return nlohmann::json{
            {"A", {{"X", 0.0f}, {"Y", 0.0f}}},
            {"B", {{"X", 1.0f}, {"Y", 0.0f}}},
            {"Color", {{"R", 1.0f}, {"G", 1.0f}, {"B", 1.0f}, {"A", 1.0f}}},
            {"Thickness", 1.0f}
        }; },
        COMPONENT_OPS(ECS::Components::ShapeLine2D)
    },

    // Light 2D
    {
        "Light 2D", "Light2D", "ECS::Components::Light2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderLight2D(d, e, w); },
        []() { return nlohmann::json{
            {"LightType", 0},
            {"Position", {{"X", 0.0f}, {"Y", 0.0f}, {"Z", 0.0f}}},
            {"Direction", {{"X", 0.0f}, {"Y", -1.0f}, {"Z", 0.0f}}},
            {"Color", {{"R", 1.0f}, {"G", 1.0f}, {"B", 1.0f}, {"A", 1.0f}}},
            {"Intensity", 1.0f}, {"Range", 10.0f}, {"CastsShadows", false}
        }; },
        COMPONENT_OPS(ECS::Components::Light2D)
    },


    // Animation State 2D
    {
        "Animation State 2D", "AnimationState2D", "ECS::Components::AnimationState2D", true,
        [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderAnimationState2D(d, e, w); },
        []() { return nlohmann::json{
            {"CurrentFrame", 0}, {"TimeAccumulator", 0.0f}, {"Finished", false}
        }; },
        COMPONENT_OPS(ECS::Components::AnimationState2D)
    },

    // Audio Source
    {
        "Audio Source",                    // DisplayName 
        "AudioSource",                     // TypeName in JSON *match entityserializerzz
        "ECS::Components::AudioSource",    // FullTypeName (for clarity)
        true,                              // Can byebye

        // RenderUI -> use ComponentUI's RenderAudioSource
        [](ComponentUI& ui, nlohmann::json& data, ECS::Entity e, ECS::World* w)
        {
            ui.RenderAudioSource(data, e, w);
        },

        // Defaults -> initial JSON for a new AudioSource
        []() -> nlohmann::json
        {
            return nlohmann::json{
                { "CueId",       0 },
                { "Volume",      1.0f },
                { "Pitch",       1.0f },
                { "Loop",        false },
                { "PlayOnStart", false },
                { "Spatial3D",   false }
            };
        },

        // Has Component
        [](ECS::World* world, ECS::Entity e) -> bool
        {
            return world->Has<ECS::Components::AudioSource>(e);
        },

        // Add Component
        [](ECS::World* world, ECS::Entity e, const nlohmann::json& data)
        {
            ECS::Components::AudioSource comp{};
            from_json(data, comp);  // uses your NLOHMANN_DEFINE_TYPE_* mapping
            world->Add<ECS::Components::AudioSource>(e, comp);
        },

        // Remove Component
        [](ECS::World* world, ECS::Entity e)
        {
            world->Remove<ECS::Components::AudioSource>(e);
        },

        // Apply To Entity (update existing component from JSON)
        [](ECS::World* world, ECS::Entity e, const nlohmann::json& data)
        {
            auto& comp = world->Get<ECS::Components::AudioSource>(e);
            from_json(data, comp);
        }
    },

    // Layer
    {
        "Layer 2D", "Layer", "ECS::Components::Layer", true,
            [](ComponentUI& ui, nlohmann::json& d, ECS::Entity e, ECS::World* w) { ui.RenderLayer2D(d, e, w); },
            []() { return nlohmann::json{
                {"Id", 0}}; },
            COMPONENT_OPS(ECS::Components::Layer)
    }

};

// -----------------------------------------------------------------------------
// Registry Class
// -----------------------------------------------------------------------------

// Returns the full component metadata list
const std::vector<ComponentUIMetadata>& ComponentRegistryUI::GetAll() {
    return m_registry;
}

// Finds a single component type using either its short or full type name
const ComponentUIMetadata* ComponentRegistryUI::Find(const std::string& typeName) {
    for (const auto& meta : m_registry) {
        if (meta.TypeName == typeName || meta.FullTypeName == typeName) {
            return &meta;  // Found it
        }
    }
    return nullptr;
}
