<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <AssemblyName>EchoesBelow</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Reference the engine's Script API -->
    <Reference Include="GrapeEngine.Scripting">
	  <HintPath>$(MSBuildThisFileDirectory)..\build\$(Configuration)\GrapeEngine.Scripting.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

</Project>
