/* Start Header *****************************************************************/
/*!
\file   CCD2D.h
\author Dalton Koh Shi Hao (100%)
\par d.koh@digipen.edu
\brief Speculative-contacts prepass for fast dynamic bodies.
*/
/* End Header *******************************************************************/

#ifndef ENGINE_PHYSICS2D_CCD2D_H
#define ENGINE_PHYSICS2D_CCD2D_H

#include "physics2d/PhysicsConfig2D.h"
#include "physics2d/PhysicsData2D.h"
#include <vector>

namespace Engine::Physics2D {
    class CCD2D {
    public:
        /**
         * @brief Inflate shallow non-trigger contacts for very fast relative motion.
         * @param config Global physics configuration.
         * @param bodies Runtime body cache.
         * @param contacts Contact constraints generated by narrowphase.
         */
        void ApplySpeculativeContacts(
            const PhysicsConfig2D& config,
            std::vector<BodyRuntime2D>& bodies,
            std::vector<ContactConstraint2D>& contacts) const;
    };
}

#endif
